### ISSUE TITLE
gdax/order_book is outdated on pypi

### ISSUE THREAD

**Issue by bsouthern** [danpaquin/gdax-python#101]
When installing gdax with pip, the order_book module errors on __init__().  The gdax/order_book __init__() method on github solves this issue.

`order_book = gdax.OrderBook()
  File "/usr/local/lib/python3.5/dist-packages/gdax/order_book.py", line 20, in __init__
    self._client = PublicClient(product_id=product_id)
TypeError: __init__() got an unexpected keyword argument 'product_id'`

**Comment by cpjolicoeur** [comment]
For reference #74 solved the issues.  Just needs to be pushed
