### ISSUE TITLE
websocket authentication

### ISSUE THREAD

**Issue by Serpens66** [danpaquin/gdax-python#102]
For which python version is your code?
I'm running python 3.4 and I get an error with this line:
sub_params['signature'] = signature_b64

TypeError: b'...=' is not JSON serializable

Therefore I added ".decode("utf-8")".

I did not use your whole project, since I'm only interested in the websocket authentication part.
My script is able to subscribe to any pair succesfully, but when I add the authentication stuff I get not a single message from gdax.

```
sub_params = {"type": "subscribe", "product_ids": [self.pair]}

timestamp = str(time.time())
message = timestamp + 'GET' + '/users/self'
message = message.encode('ascii')
hmac_key = base64.b64decode(self.secret)
signature = hmac.new(hmac_key, message, hashlib.sha256)
signature_b64 = base64.b64encode(signature.digest())
sub_params['signature'] = signature_b64.decode("utf-8")
sub_params['key'] = self.key
sub_params['passphrase'] = self.passphrase
sub_params['timestamp'] = timestamp

message_json = json.dumps(sub_params)
self.send(message_json)
```

without the part in the middle I get messages from websocket. But with the authentication stuff, I get nothing...
Can you imagine what the problem can be? Does the authentication works with you script? which python version?

**Comment by s0nik42** [comment]
Hi Serpens66,

 Same I you, , I make it worked with : signature_b64.decode("ascii")

Have a nice day,

**Comment by Serpens66** [comment]
thank you.
I tested it again and found out that "utf-8"" seems also to work, but the problem was that directly after the code above I made:
`           # message_data = {"type": "heartbeat", "on": True}
            # message_json = json.dumps(message_data)
            # self.send(message_json)`
and for some reason then I only get heartbeat, but no product_id information.

When I leave out the authentication part from my first post, then I get product_id stuff and heartbeat.

**Comment by jameslin101** [comment]
I'm having trouble with the websocket authentication code as well, after making the changes above. It is simply stuck. I'm also able to get info without authentication

**Comment by Serpens66** [comment]
from what I saw, you are not missing much.
With authentication the only change is, that some messages contain profile_id and user_id.
I saw eg no message about my balance, as I expected for a authenticated websocket.

**Comment by jameslin101** [comment]
what about orders? I'm assuming they should be faster under websocket vs rest

**Comment by Serpens66** [comment]
You mean placing new orders? From what I can see in documentation, you can not place orders via webocket https://docs.gdax.com/#websocket-feed , am I wrong?

**Comment by jameslin101** [comment]
Oh wow I think you are right. I guess you have to do it either on rest or fix. Thanks -- I had made an assumption that order messages were for new orders.

**Comment by s0nik42** [comment]
you receive additionnal information on the orders you placed, but to place an order you have to use REST or FIX interfaces.

Serpens, have you tried to use the  authenticated_client.py sample and only add the signature_b64.decode ? does it work ?
