### ISSUE TITLE
{u'message': u'price too precise (2706.9300000000003)'}

### ISSUE THREAD

**Issue by Londo-Mollari** [danpaquin/gdax-python#110]
Hello,
I believe I have found an issue with the Python JSON module that makes it impossible to trade under certain circumstances.

For instance:
Selling 0.01372113 BTC @ 2706.93 (and many other values) yields the following result:
`{u'message': u'price too precise (2706.9300000000003)'}`

Please keep in mind that the values passed to both buy and sell functions have been truncated, and verified, to exactly two decimal places for dollars, and eight decimal places for BTC.

I achieved truncation by multiplying the floating point price by 100, converting it to an int, converting it back to a float, and then dividing by 100.  This isn't as elegant as a more flexible option, but I had been trying to debug this issue for a while.

Then I found these:
[https://stackoverflow.com/questions/1447287/format-floats-with-standard-json-module](url)
[https://stackoverflow.com/questions/32145824/python-forcing-precision-on-a-floating-point-number-in-json](url)

Is there a way we can engineer around the JSON precision issue and build it into the library?

Thanks.

**Comment by Londo-Mollari** [comment]
I just wanted to add a note that this error started happening after I updated the library and changed from params to kwargs.  I do not know if this has an impact on a floating point value reaching the JSON libray.

**Comment by mcardillo55** [comment]
I've had a better experience using the built in Decimal class, as the OrderBook does as well.

**Comment by acontry** [comment]
You may have tried to truncate the number, but floating point can't represent all numbers exactly so you end up with some dangling values in the decimal place in some cases. Best to convert to Decimal (per @mcardillo55's suggestion) to guarantee the number of decimal places.

I think the best thing to do for the library is to specify in documentation that Decimal should be used for the appropriate fields (done in my PR #81).

**Comment by mrbodoia** [comment]
If you don't want to use Decimals, you can also just use strings as the keyword arguments to the API call. For example, `order_price = '{0:.2f}'.format(order_price)` is a quick and dirty way to reformat a `float` order price into a string that the API will accept. You can do the same thing for your order size with `order_size = '{0:.8f}'.format(order_size)`.

**Comment by Londo-Mollari** [comment]
Hi guys,
Thanks for the pointers (if this was C that would be a joke).  I have adopted using the Decimal class and I do send the numbers as a string, now, to the buy/sell function.  If the documentation is being updated per acontry, then all my questions have been answered.

Please let me know if I'm wrong closing this issue, but for now I'll hit that button.  Thanks many times over, everyone.
