### ISSUE TITLE
Withdraws - Invalid scope

### ISSUE THREAD

**Issue by michaelDomingues** [danpaquin/gdax-python#114]
Hey guys,

I always end with an invalid scope message for the withdraws call to the API. Am I missing a Bearer token or something like that?  So far I've tested only in sandbox.
What am I missing?

Thanks

**Comment by danpaquin** [comment]
Hi Michael, thanks for reaching out.  I would try on the live exchange as the sandbox for GDAX is being supported less and less.

**Comment by michaelDomingues** [comment]
Thanks @danpaquin. Indeed that day after day is being annoying using sandbox. 😞

**Comment by danpaquin** [comment]
Has this been resolved?
