### ISSUE TITLE
Running the API

### ISSUE THREAD

**Issue by nikilster** [danpaquin/gdax-python#115]
Hey! Thanks for making this - looks awesome!!

Trying to figure out how to get the API to run.  I did a pip install, and have a python file with these two lines from the README:

```
import gdax
public_client = gdax.PublicClient()
```

Keep getting this error though:

> AttributeError: 'module' object has no attribute 'PublicClient'

Tried a bunch of things but not sure whats going on - appreciate the help!

**Comment by nikilster** [comment]
The file was called gdax.py and apparently conflicted with the module name.  Renaming the file and removing the .pyc fixed it!

**Comment by Klutix** [comment]
Thanks i made the same mistake!
