### ISSUE TITLE
version tags

### ISSUE THREAD

**Issue by adb** [danpaquin/gdax-python#124]
Hi Daniel, could I trouble you to add tags (and possibly branches) for your releases, at least the latest one? I'd like to be able to reference a stable version in a readable way, e.g. from bazel WORKSPACE files.

**Comment by danpaquin** [comment]
Hello @adb we are being careful to no longer break backwards comparability moving forward.  I will do my best to implement better documentation of version's as well.  If you would like to get the ball rolling, please reach out to me directly.
