### ISSUE TITLE
Authenticated Websocket Problem

### ISSUE THREAD

**Issue by NehrenD** [danpaquin/gdax-python#128]
I am trying to setup a websocket user channel for my orders/execution. When running the code I get a JSON error during the json.dumps: _`TypeError: Object of type 'bytes' is not JSON serializable`_. 
From what I can gather this is due to the signature being a binary b64encoded field. I tried to decode the signature using signature_b64.decode('ascii') (tried 'utf-8' as well) but I get a Bad signature reply
Using: Python 3.6.1 on Mac OS. Please Help!

**Comment by drewrice2** [comment]
@NehrenD would you mind posting the whole stacktrace?

**Comment by hydroplosion** [comment]
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/gdax-1.0.6-py3.6.egg/gdax/websocket_client.py", line 39, in _go
    self._connect()
  File "/usr/local/lib/python3.6/dist-packages/gdax-1.0.6-py3.6.egg/gdax/websocket_client.py", line 76, in _connect
    self.ws.send(json.dumps(sub_params))
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

**Comment by drewrice2** [comment]
@NehrenD @hydroplosion i think it's a double-encoding issue. looking into this.

**Comment by hydroplosion** [comment]
`def startWebSocket():
    wsClient = gdaxWebSocket()
    wsClient.start()

class gdaxWebSocket(gdax.WebsocketClient):
    def on_open(self):
        self.channels = ["user", "matches"]
        self.products = products
        self.url = "wss://ws-feed.gdax.com"
        self.auth = True
        self.api_key = <API>
        self.api_secret = <SECRET>
        self.api_passphrase = <UUID>
        self.message_count = 0
    def on_message(self, msg):
        self.message_count += 1
        print(str(msg))
    def on_close(self):
        print("websocket closed")`

**Comment by NehrenD** [comment]
Thank you guys for the help and thank you @hydroplosion for following up when I didn't! I have been away and did check in on this.

**Comment by aviators99** [comment]
I tried hydroplosions code, and it's still sending all of the messages.  Not just matching ones.  It seems that the gdaxWebSocket code is ignoring the self.channels assignment?

**Comment by llatseattle** [comment]
I think so. As far as my code, it is sending all the information
