### ISSUE TITLE
Update installation requirements

### ISSUE THREAD

**Issue by acontry** [danpaquin/gdax-python#129]
Pymongo was added without updating setup.py

**Comment by lirenz** [comment]
Instead of just supporting mongo, I think WebsocketClient should accept some sort of abstract writer class with only __init__ and insert defined. That way we can insert to file, mysql, etc.

**Comment by drewrice2** [comment]
@lirenz nice call! i'll work on that when i have time. although, mysql doesn't have native JSON support as far as i know. but you're totally right that a writer class makes sense here.

@danpaquin would you mind adding `pymongo` to `setup.py`? definitely an oversight on my part not to include the extra package in `setup.py`.

**Comment by danpaquin** [comment]
Thanks @drewrice2
