### ISSUE TITLE
Deposit and withdrawal calls are out of date

### ISSUE THREAD

**Issue by ericscheier** [danpaquin/GDAX-Python#13]
https://docs.gdax.com/#deposits

It looks like GDAX is now requesting specific parameters for transferring among coinbase vs. other payment methods.

**Comment by danpaquin** [comment]
Hi Eric,

I appreciate this callout.  I will commit changes shortly unless someone else would like to step in.

**Comment by danpaquin** [comment]
Thank you for your updates, Eric!

This is being closed due to #14
