### ISSUE TITLE
Error in 'import gdax' after updating to new version

### ISSUE THREAD

**Issue by kopron** [danpaquin/gdax-python#130]
Everything was working well with a month old build of gdax-python. I updated with "sudo pip install gdax" and now I get this message when I try to 'import gdax'

Traceback (most recent call last):
  File "backfill.py", line 2, in <module>
    import gdax
  File "/usr/local/lib/python2.7/dist-packages/gdax/__init__.py", line 3, in <module>
    from gdax.websocket_client import WebsocketClient
  File "/usr/local/lib/python2.7/dist-packages/gdax/websocket_client.py", line 11, in <module>
    from websocket import create_connection, WebSocketConnectionClosedException
  File "/home/i/coincatcher/websocket.py", line 2, in <module>
    class myWebsocketClient(gdax.WebsocketClient):
AttributeError: 'module' object has no attribute 'WebsocketClient'

I tried removing and reinstalling. Still the same issue. Any ideas? Thanks!

**Comment by drewrice2** [comment]
i believe i'm on the latest version, too. i can't seem to recreate your error. 

`from gdax.websocket_client import WebsocketClient` works for me. not sure why the call in `__init__.py` would fail. 

double check that you don't have two conflicting versions or something along those lines. for the record `pip install --upgrade gdax` should be the update command. 

i'll keep poking around. let me know if you encounter any other weird behaviors or errors.

**Comment by kopron** [comment]
Ok, thanks for the response. I assume it's a problem on my end so I'll close the issue for now. If I find any bug that could affect others I'll send you a note.
