### ISSUE TITLE
get_product_historic_rates date range problem

### ISSUE THREAD

**Issue by r-kalma** [danpaquin/gdax-python#133]
The start time doesn't seem to impact the result of the historical data read:

```
gg = pd.DataFrame(gd_public.get_product_historic_rates('ETH-BTC', start = 1508490000, granularity=60))
print(gg.head(1))
print(gg.tail(1))

gg = pd.DataFrame(gd_public.get_product_historic_rates('ETH-BTC', start = 1508454000, granularity=60))
print(gg.head(1))
print(gg.tail(1))
```

returns:
            0        1        2        3        4         5
0  1508495280  0.05386  0.05386  0.05386  0.05386  0.627107
              0        1        2        3        4         5
175  **1508472060**  0.05411  0.05411  0.05411  0.05411  1.116996
            0        1        2        3        4         5
0  1508495280  0.05386  0.05386  0.05386  0.05386  0.627107
              0        1        2        3        4         5
175  **1508472060**  0.05411  0.05411  0.05411  0.05411  1.116996

Any insights on why this is?

**Comment by danpaquin** [comment]
It is an error from GDAX.  I believe issue #70 is looking for an explanation for this and perhaps a local solution for this project.  Please share your specifics on that thread.
