### ISSUE TITLE
PIp version doesn't match repo

### ISSUE THREAD

**Issue by dahifi** [danpaquin/gdax-python#134]
Was having a problem with the websocket client, was trying to subscribe to the ticker channel but keep getting the general book feed instead. Started debugging the code in my python packages directory and noticed that the code was different from the source here on Github. 

Looks like pip version is 1.0.6, but I can't tell what version the repo is currently on. Removed the package and cloned the repo but having errors with threading. 

Just looking for some clarification. Thanks,

**Comment by dahifi** [comment]
Just to clarify what I'm doing: 

`
class Coin:
    def __init__(self, product):
        self.product_id = product
        self.best_bid = 0.0
        self.best_ask = 0.0

coins = ["BTC-USD", "ETH-USD", "ETH-BTC"]

class myArbitrageBot(gdax.WebsocketClient):
    coins = {}

    def on_open(self):
        self.channels = ["ticker"]
        self.products = ["ETH-BTC"]#["BTC-USD", "ETH-USD", "ETH-BTC"]
        for product in self.products:
            self.coins[product] = Coin(product)

    def on_message(self, msg):
        # product_id = msg["product_id"]
        # best_bid = msg["best_bid"]
        # best_ask = msg["best_ask"]
        wsClient.close()
        print msg


wsClient = myArbitrageBot()
wsClient.on_open()
wsClient.start()`

**Comment by mjmj** [comment]
Yeah, that threw me for a loop when trying to follow the readme. cloned the repo and installed manually (not using pip) and moving in the right direction now. Haven't noticed errors with threading just yet.

**Comment by ZZZWENG** [comment]
@dahifi You are joining the thread inside the thread itself.  (wsClient.close() calls thread.join() under the hood). So you might want to try:

`class myArbitrageBot(gdax.WebsocketClient):
    coins = {}

    def on_open(self):
        self.channels = ["ticker"]
        self.products = ["ETH-BTC"]
        print 'assigning coins...'
        for product in self.products:
            self.coins[product] = Coin(product)

    def on_message(self, msg):
#         wsClient.close()
        print 'MSG', msg


wsClient = myArbitrageBot()
wsClient.start()
wsClient.close()
`

**Comment by dahifi** [comment]
Yea, I was able to clear up the thread issue and get the code working properly, but the issue here still remains that the pip version doesn't match the codebase here and there is no clear versioning to allow people to determine what that is. 

I'm not sure if that falls outside of the scope of being an issue or not.
