### ISSUE TITLE
does websocket offer callback?

### ISSUE THREAD

**Issue by dzhlovegithub** [danpaquin/gdax-python#142]
does websocket offer callback for your own orders, such as on_order, on_trade to track my own orders?

**Comment by danpaquin** [comment]
Unfortunately GDAX does not offer this natively. According to their developers, you must keep a local copy of your orders locally. Depending how how you implement that, you could add triggers to the websocket client.

**Comment by lirenz** [comment]
@dzhlovegithub Can you subscribe to the "user" channel and write special logic in on_message to do what you want?

**Comment by dzhlovegithub** [comment]
@lirenz thank you!
