### ISSUE TITLE
AttributeError: 'AuthenticatedClient' object has no attribute 'cancelAll'

### ISSUE THREAD

**Issue by ReedJessen** [danpaquin/GDAX-Python#15]
authClient.cancelAll() doesn't seem to be working. 

Any ideas?

```python
import GDAX

authClient = GDAX.AuthenticatedClient(api_key, secret, passphrase, product_id="BTC-USD")

authClient.cancelAll()
```
```
Traceback (most recent call last):
  File "C:/PythonApps/gdax/run.py", line 42, in <module>
    authClient.cancelAll()
AttributeError: 'AuthenticatedClient' object has no attribute 'cancelAll'
```

 Very willing to believe that this is something I am doing wrong but still can't figure out what it might be.  I do see that `AuthenticatedClient.cancelAll()` exists in [AuthenticatedClient.py](https://github.com/danpaquin/GDAX-Python/blob/master/GDAX/AuthenticatedClient.py).

**Comment by danpaquin** [comment]
Hey Reed, thank you for reaching out!  I wish I had the answer, but I do not have enough information to be 100% confident.  

Did you install the package through PIP or a manual method?  The cancelAll() method is quite recent and has not been added to the current version of PIP.  I will update the PIP package shortly and post here when complete.

If this does not resolve the issue, please provide more information regarding how you are including the GDAX wrapper in your project and I will do my best to help.

**Comment by danpaquin** [comment]
PIP has been updated to version 0.2.2, please update your project:

`python -m pip install --upgrade gdax`

**Comment by ReedJessen** [comment]
I am sure that's what it is. Will reinstall next week and close issue when it works. Thanks for your help and quick response.

**Comment by ReedJessen** [comment]
@danpaquin This solved the problem.  The version on pip was behind the github version.  Updating the pip version to the current status fixed it.  Thanks for your help on this.  Love the library.
