### ISSUE TITLE
Using OrderBook class to Interact with _bids and _asks Live

### ISSUE THREAD

**Issue by Vacant0mens** [danpaquin/gdax-python#154]
Is there a proper usage for using the `OrderBook` class to do live interactions with the RBTrees/orderbooks? Every time I try to do it, it seems like the `_bids` and `_asks` RBTree's don't update and I keep getting the same list back when I use `_bids.nlargest(20)` or `_asks.nsmallest(20)`.

Any ideas?

**Comment by mcardillo55** [comment]
What are you trying to do exactly? I don't think _bids or _asks were designed to be interacted with directly, hence the underscore at the start. Have you tried using .get_asks(price) and .get_bids(price)?

**Comment by Vacant0mens** [comment]
the `.get_asks(price)` and `.get_bids(price)` just call `_asks.get(price)` or `_bids.get(price)` respectively (which is just a bintree search for the key). the `get_bid()` and `.get_ask()` call `_bids.max_key()` or `_asks.min_key()` respectively (which pulls the highest or lowest valued key). So I'm not sure what you mean by "_bids or asks were[n't] designed to be interacted with directly." I'm not doing anything that's much different than that, I'm just not making a two-line method for it. Or is that two-line method the python way of "indirectly interacting"?

What I'm trying to do is get the top 20 bids and the bottom 20 asks so I can do some calculations against them.

Also, I just realized that the `.nlargest(20)` and `.nsmallest(20)` pull the largest/smallest key/value pair, not  just the largest/smallest keys. But I'm trying to pull the 20 largest/smallest **keys** (or 'price' fields).

**Comment by Vacant0mens** [comment]
After some testing, it seems (not sure if I can confirm this or not) that the `._bids` and `._asks` RBTrees get started on `__init__()` but then stop updating as soon as my `on_message()` gets called for the first time.

Is there a way to keep the trees updating while I query them for prices and such? the `OrderBookConsole()` class seems to do it, but I'm not sure what I'm doing different.

**Comment by Vacant0mens** [comment]
Decided to write my own OrderBook class that does what i need.
