### ISSUE TITLE
AttributeError: 'myWebsocketClient' object has no attribute 'start'

### ISSUE THREAD

**Issue by fabianbaier** [danpaquin/GDAX-Python#16]
Following the readme.md:
```
import GDAX, time
class myWebsocketClient(GDAX.WebsocketClient):
    def onOpen(self):
        self.MessageCount = 0
        print "Lets count the messages!"
    def onMessage(self, msg):
        print "Message type:", msg["type"], "\t@ %.3f" % float(msg["price"])
        self.MessageCount += 1
    def onClose(self):
        print "-- Goodbye! --"

wsClient = myWebsocketClient()
wsClient.start()
# Do some logic with the data
while (wsClient.MessageCount < 500):
    print "\nMessageCount =", "%i \n" % wsClient.MessageCount
    time.sleep(1)
wsClient.close()
```

Gives error:
```Traceback (most recent call last):
  File "myscript.py", line 90, in <module>
    wsClient.start()
AttributeError: 'myWebsocketClient' object has no attribute 'start'
```

environment:
```
GDAX==0.2.0
numpy==1.12.1
pandas==0.19.2
python-dateutil==2.6.0
pytz==2016.10
requests==2.13.0
six==1.10.0
websocket-client==0.40.0

shell$ python --version
Python 3.5.2 :: Continuum Analytics, Inc.
```

**Comment by wgreene18** [comment]
I've installed GDAX (pip install GDAX).  I get the following error when I try to import the package in python:

import GDAX
Traceback (most recent call last):

  File "<ipython-input-2-bbe99608e9f3>", line 1, in <module>
    import GDAX

  File "/Users/williamgreene/Library/Mobile Documents/com~apple~CloudDocs/btc/GDAX.py", line 4, in <module>
    publicClient = GDAX.PublicClient(product_id="ETC-USD")

AttributeError: module 'GDAX' has no attribute 'PublicClient'

**Comment by wgreene18** [comment]
I have installed GDAX (pip install GDAX). I get the below error when I try to import the package in Python. Any help would be greatly appreciated. 

import GDAX
Traceback (most recent call last):

  File "<ipython-input-2-bbe99608e9f3>", line 1, in <module>
    import GDAX

  File "/Users/btc/GDAX.py", line 4, in <module>
    publicClient = GDAX.PublicClient(product_id="ETC-USD")

AttributeError: module 'GDAX' has no attribute 'PublicClient'

**Comment by wgreene18** [comment]
I have installed GDAX (pip install GDAX). When I try to import GDAX in Python, I get the below error. Any help would be greatly appreciated. Thanks!

import GDAX
Traceback (most recent call last):

  File "<ipython-input-1-bbe99608e9f3>", line 1, in <module>
    import GDAX

  File "/Users/btc/GDAX.py", line 3, in <module>
    publicClient = GDAX.PublicClient()

AttributeError: module 'GDAX' has no attribute 'PublicClient'

**Comment by danpaquin** [comment]
Hello fabianbaier,

Are you still experiencing these issues?  I tested this on Python 3.5 updated dependencies and GDAX 2.2 and it works fine.  Please update GDAX and let me know if you continue to experience this.

Thank you!
Dan

**Comment by danpaquin** [comment]
Closing this out. Please create a new thread if you continue to experience this.
