### ISSUE TITLE
pytest

### ISSUE THREAD

**Issue by rwik1994** [danpaquin/gdax-python#161]
I ran python -m pytest and got the following error:

============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/rwik/Kraysoft/gdax/gdax-python, inifile: 
collected 0 items / 1 errors 

=================================== ERRORS====================================
_________________ ERROR collecting tests/test_public_client.py _________________
tests/test_public_client.py:2: in <module>
    import gdax
gdax/__init__.py:3: in <module>
    from gdax.websocket_client import WebsocketClient
gdax/websocket_client.py:16: in <module>
    from pymongo import MongoClient
E   ImportError: No module named pymongo
=========================== 1 error in 0.23 seconds ============================

**Comment by jlane9** [comment]
@rwik1994 you must run either 
`pip install pymongo` or `pip install -r requirements.txt`
