### ISSUE TITLE
Get current exchange rate for a particular product 

### ISSUE THREAD

**Issue by Diptayan1995** [danpaquin/gdax-python#167]
Is there any method available to get the current exchange rate for a particular product (say "ETH-USD') ?

**Comment by tolidano** [comment]
You can check the README for such things - 

get_product_ticker
# Get the product ticker for a specific product.
public_client.get_product_ticker(product_id='ETH-USD')

**Comment by mcardillo55** [comment]
If you're using an OrderBook, you can also use OrderBook.get_current_ticker().
