### ISSUE TITLE
NotAnIssue:  Implementation Code, Garbage Examples...

### ISSUE THREAD

**Issue by derenma** [danpaquin/gdax-python#178]
Since most people who trade are not _generally_ code inclined, I would like to post an implementation of this module.  Again, this is not an issue, not a problem, and was originally designed for multi-threaded code.

However, since I have the audacity to make such an "issue" I will be posting some cleaner demo code soon.   

(It's a hack job from some of my private code, but some people might want to adapt for their own use.)

https://github.com/derenma/gdax-basic

**Comment by danpaquin** [comment]
I really love this, but the goal of this project is to provide a first-step implementation of the API for others to wrap into their own projects how they please.

This is a great example of how you can take a not-so perfect project and make it work for your specific needs. Keep up the great work @derenma!
