### ISSUE TITLE
Using pymongo, server timed out error

### ISSUE THREAD

**Issue by htso** [danpaquin/gdax-python#182]
I'm merely running your example code below, it first succeeded, but after a few seconds, I got this error 

> Exception in thread Thread-5:
> Traceback (most recent call last):
>   File "/home/rspace/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/home/rspace/anaconda3/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/gdax-1.0.6-py3.6.egg/gdax/websocket_client.py", line 41, in _go
>     self._listen()
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/gdax-1.0.6-py3.6.egg/gdax/websocket_client.py", line 90, in _listen
>     self.on_message(msg)
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/gdax-1.0.6-py3.6.egg/gdax/websocket_client.py", line 119, in on_message
>     self.mongo_collection.insert_one(msg)
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/pymongo/collection.py", line 682, in insert_one
>     session=session),
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/pymongo/collection.py", line 598, in _insert
>     bypass_doc_val, session)
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/pymongo/collection.py", line 578, in _insert_one
>     True, _insert_command, session)
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1098, in _retryable_write
>     with self._tmp_session(session) as s:
>   File "/home/rspace/anaconda3/lib/python3.6/contextlib.py", line 81, in __enter__
>     return next(self.gen)
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1404, in _tmp_session
>     s = self._ensure_session(session)
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1391, in _ensure_session
>     return self.start_session(causal_consistency=False)
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1369, in start_session
>     server_session = self._get_server_session()
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1377, in _get_server_session
>     return self._topology.get_server_session()
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/pymongo/topology.py", line 416, in get_server_session
>     None)
>   File "/home/rspace/anaconda3/lib/python3.6/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
>     self._error_message(selector))
**> pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused**

====== example code =================================
from pymongo import MongoClient
import gdax
mongo_client = MongoClient('mongodb://localhost:27017/')

db = mongo_client.cryptocurrency_database
BTC_collection = db.BTC_collection

wsClient = gdax.WebsocketClient(url="wss://ws-feed.gdax.com", products="BTC-USD",
    mongo_collection=BTC_collection, should_print=False)
wsClient.start()

**Comment by hiemal** [comment]
You didn't start your mongo on that port; did you run `mongod`?

**Comment by htso** [comment]
Excellent observation! That's exactly what happened. After `mongod`, it's now working. Thank you.
