### ISSUE TITLE
OrderBook() crashes

### ISSUE THREAD

**Issue by illera88** [danpaquin/gdax-python#189]
Crash with `OrderBook()`
```
C:\>C:\Python36-64\python.exe c:\python36-64\lib\site-packages\gdax\order_book.py
Traceback (most recent call last):
  File "c:\python36-64\lib\site-packages\gdax\order_book.py", line 236, in <module>
    order_book = OrderBook()
  File "c:\python36-64\lib\site-packages\gdax\order_book.py", line 20, in __init__
    self._client = PublicClient(product_id=product_id)
TypeError: __init__() got an unexpected keyword argument 'product_id'
```

Indeed `PublicClient` is not expecting any `product_id` parameter:

```
def __init__(self, api_url='https://api.gdax.com'):
        """Create GDAX API public client.

        Args:
            api_url (Optional[str]): API URL. Defaults to GDAX API.

        """
        self.url = api_url.rstrip('/')
```

**Comment by danpaquin** [comment]
@illera88 We made a decision quite some time ago to not include product_id in init to ensure each call is being made as expected.  Since your implementation may vary, feel free to add self.product_id!  If more people request it, a PR might be a way to attract attention to the idea.

Thanks for your support!
Dan

**Comment by jonnylangefeld** [comment]
I am having the same issue. Running the example results in above error:

    import gdax, time
    order_book = gdax.OrderBook(product_id='BTC-USD')
    order_book.start()
    time.sleep(10)
    order_book.close()

If I remove `product_id=product_id` from `self._client = PublicClient(product_id=product_id)` then I get the next error:

    File "/usr/local/lib/python3.6/site-packages/gdax/order_book.py", line 22, in __init__
    self._log_to = log_to
    NameError: name 'log_to' is not defined
