### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by andrewbain** [danpaquin/gdax-python#193]
I am suddenly getting this error when I run gdax.PublicClient() and gdax.AuthenticatedClient(API_KEY, API_SECRET,API_PASS) - it didnt happen before

AttributeError: module 'gdax' has no attribute 'PublicClient'

**Comment by danpaquin** [comment]
This must be an issue with pip.  Please update your directory with the master branch here on Github and follow PR #260 for an idea of when PIP will be updated.
