### ISSUE TITLE
Information on the base64 decoding

### ISSUE THREAD

**Issue by Masondeanm** [danpaquin/gdax-python#196]
First off I'd like to apologize if this is an inappropriate place to put this, but I've tried for hours to figure this out and I can't think of anywhere else to turn. I don't know how to use Python, other than very simple stuff. I've built my own wrapper for the Binance API in Lua, the language I know best, and I'm trying to do the same for GDAX. However, I've run into a problem I can't solve: base 64 decoding my secret key. Every single source I've tried, be it online, in the mac terminal with the base64 function and OpenSSL's base64 decoder; I even built my own from scratch. Every single one either doesn't work, or gives me something completely different. I'm wondering if anyone here can explain to me how the base64 encoding and decoding that were supposed to be using for GDAX works.

**Comment by smalbadger** [comment]
I'm not sure how the actual encoding works, so I apologize in advance if this isn't the answer you're looking for. I didn't have to encode my passphrase, key, or secret after getting it from GDAX. If you go to your account, create a new API key, and just copy the key, passphrase, and secret as parameters into the AuthenticatedClient() constructor, you should be good to go. It did take a while after I created the API key for it to get updated in their servers, so don't expect it to work right after you create the API key. Once again, sorry if this isn't what you're looking for

**Comment by Masondeanm** [comment]
I just saw, from the official API page "Remember to first base64-decode the **alphanumeric** secret string." The secret string I have is not alphanumeric. Am I just being really dumb or is this just wrong?

**Comment by Masondeanm** [comment]
I figured out a way to get it working.

**Comment by Masondeanm** [comment]
@smalbadger How long did it take for the key to get updated? Like over an hour?
