### ISSUE TITLE
price too precise

### ISSUE THREAD

**Issue by Diptayan1995** [danpaquin/gdax-python#198]
I was placing a buy order at buyprice 816.95 with buy method . But it shows {u'message': u'price too precise (816.9499999999999)'} sometimes . how to avoid this problem?

**Comment by acontry** [comment]
All values are sent over the wire as strings - if you do nothing, your float is implicitly converted to string along with its imperfect precision. [Here are some example solutions](https://stackoverflow.com/questions/15076310/format-python-decimal-object-to-a-specified-precision).

**Comment by R7AL** [comment]
just do auth_client.buy(price= round(price,2), size=size, product_id='LTC-USD')
notice: round(price,2)
