### ISSUE TITLE
Accept pull requests for test module?

### ISSUE THREAD

**Issue by ReedJessen** [danpaquin/GDAX-Python#20]
Hi @danpaquin, 

Would you accept a pull request for a suite of unit tests?  It seems that sense people are using this library to trade money, there should be a baseline set of tests.  I would like to put these together.

With your go-ahead, I would expect to work on this over the next 3-4 weeks.

**Comment by danpaquin** [comment]
Hi @reedjessen 

This package really needs some good unit tests to help us build and maintain the project in an efficient way.  Please keep us updated on your progress.  There were some commits made in the development branch if it might help, but do not feel like you must use it.

**Comment by ReedJessen** [comment]
Wonderful.  I will start a new branch with unit tests in it's own file, tests.py.  I'll then submit a WIP pull request and everyone can track my progress and contribute if desired.

Closing issue.

**Comment by ReedJessen** [comment]
Hi @danpaquin,  I am so sorry but I will not be able to participate on this project any longer.  My wife is giving birth tomorrow and my attention is needed at home.  I apologize for backing out of this commitment and hope I have not caused too many problems.

Best Wishes,
Reed
