### ISSUE TITLE
Example that is in the documentation doesn't work

### ISSUE THREAD

**Issue by exquest** [danpaquin/gdax-python#200]
I install gdax by running `pip install gdax`

>>> import gdax
>>> p = gdax.PublicClient()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PublicClient'

Python 3.4.3 on Ubuntu 14.04

**Comment by exquest** [comment]
After manually installing it seems to work fine

**Comment by danpaquin** [comment]
I expect this to be resolved once pip is updated. Monitor PR #260 for a timeline of when PIP is updated.
