### ISSUE TITLE
How to specify a GTT buy or sell?

### ISSUE THREAD

**Issue by JoeSchm** [danpaquin/gdax-python#202]
What do I add to this statement or a similar sell statement to make it GTT (good til time)? By that I mean time in force so that it would be canceled after a stated time? I know I could use a separate line to cancel orders but the api docs say that a GTT order can be specified. Thanks,

# Buy 0.01 BTC @ 100 USD
auth_client.buy(price='100.00', #USD
               size='0.01', #BTC
               product_id='BTC-USD')

**Comment by icecoldfire** [comment]
You need to set the parameters like this:

`auth_client.sell(price='100.00',
                            size='0.01',
            product_id='BTC-USD'
                                                      type="limit",
                                                      time_in_force="GTT",
                                                      cancel_after="hour")`
