### ISSUE TITLE
Unsupported granularity

### ISSUE THREAD

**Issue by gpwood** [danpaquin/gdax-python#210]
I tried this directly from the front page:

import gdax
res=public_client.get_product_historic_rates('ETH-USD', granularity=3000)
print(res)

and got this:

{'message': 'Unsupported granularity'}

I'm using Python 3.5.4
and 

pip install gdax
Requirement already satisfied: gdax in /anaconda/lib/python3.5/site-packages
Requirement already satisfied: requests==2.13.0 in /anaconda/lib/python3.5/site-packages (from gdax)
Requirement already satisfied: bintrees==2.0.7 in /anaconda/lib/python3.5/site-packages (from gdax)
Requirement already satisfied: six==1.10.0 in /anaconda/lib/python3.5/site-packages (from gdax)
Requirement already satisfied: websocket-client==0.40.0 in /anaconda/lib/python3.5/site-packages (from gdax)

**Comment by davidmmiller7** [comment]
Just noticed the same thing. If you go to the GDAX API reference page, you'll see the accepted granularity levels:

https://docs.gdax.com/#get-account-history
"The granularity field must be one of the following values: {60, 300, 900, 3600, 21600, 86400}. Otherwise, your request will be rejected."

try this:
res=public_client.get_product_historic_rates('ETH-USD', granularity=3600)

**Comment by gpwood** [comment]
Thanks, this must be an update from the api since a couple of days ago it accepted all granularities. These values make a lot of sense though.

**Comment by sozel** [comment]
I've noticed this around third week of December 2017.  GDAX updated their API documentation and changed the acceptable granularity values.  I was relying on 1 (second) to get historical seconds data and it's no longer available.  
I also believe this isn't an issue with the Python library - I recommend we close the issue.

**Comment by ericbhanson** [comment]
Shouldn't the library should reject any values outside of those accepted by GDAX? Otherwise we're relying on an API response to correct usage, which seems like a problematic approach.

**Comment by davidmmiller7** [comment]
Update: see Pull Request #223 

This should fix it without breaking anyone's code (that wasn't already incompatible with the API)

https://github.com/danpaquin/gdax-python/pull/223

**Comment by danpaquin** [comment]
Since we merged #223 and we're going to release error handling soon, I'm closing this one out.

Please open a new issue if this persists on the master branch.
