### ISSUE TITLE
Orderbook potential loophole?

### ISSUE THREAD

**Issue by Yuanchu** [danpaquin/gdax-python#212]
In **def reset_book** of **order_book,py**, you use REST api to get a snapshot of level 3 to build the base level, but will incoming messages be missed while the reset is being done?

**Comment by Yuanchu** [comment]
In on_message, I did: **print(sequence, ' ', self._sequence)**. In reset_book, I did: **print(res['sequence'])**. And I got the following:

1052303989   -1   
1052304032
1052303990   1052304032   
1052303991   1052304032  
1052303992   1052304032 
......

Seems that the first message triggered reset_book which sends a REST request to get a level 3 snapshot. The sequence number of that snapshot is 1052304032 which is leading the messages from websocket for a while. I'm wondering if this design by GDAX is intentional, i.e. REST API leads websocket by some messages?

**Comment by neverfox** [comment]
Please see the algorithm in the GDAX documentation for building a live order book:

1. Send a subscribe message for the product(s) of interest and the full channel.
2. Queue any messages received over the websocket stream.
3. Make a REST request for the order book snapshot from the REST feed.
4. Playback queued messages, discarding sequence numbers before or equal to the snapshot sequence number.
5. Apply playback messages to the snapshot as needed (see below).
6. After playback is complete, apply real-time stream messages as they arrive.

**Comment by obixmt** [comment]
Here is a working example that should work with a cut/paste running python 2.7 and gdax-python 1.0.6
`
""" Public Websocket Ticker Feed Example
      Auth: obixmt
      Date: 12/31/2017
      Required:
        gdax-python 1.0.6
        Python 2.7
"""
import gdax, time

class myWebsocketClient(gdax.WebsocketClient):
  def on_open(self):
    self.url = "wss://ws-feed.gdax.com/"
    self.products = ["BTC-USD"]
    self.message_count = 0
    self.channels = ['ticker']
    self.type = 'ticker'
    print("\n-- Start Websocket --")

  def on_message(self, msg):
    ## This is just formatting, could be replaced with just 'print(msg)'
    if 'type' in msg:
      if msg["type"] == 'ticker':
        self.message_count += 1
        
        tmp = str(self.message_count)
        tmp += "  " + msg["product_id"]
        tmp += "\tBid {:.2f}".format(float(msg["best_bid"]))
        tmp += "  Ask {:.2f}".format(float(msg["best_ask"]))

        ## The first quote does not contain these
        if 'side' in msg:
          tmp += "\t  Last:  "
          tmp += msg["side"]
          tmp += " " + msg["last_size"]
          tmp += " @ {:.2f}".format(float(msg["price"]))
        print(tmp)

  def on_close(self):
    ## the sleep just allows the last quote to come through, not necessary
    time.sleep(1)
    print("-- Stop Websocket --")

wsClient = myWebsocketClient()
wsClient.start()

while (wsClient.message_count < 50):
  time.sleep(1)

wsClient.close()
`

**Comment by Yuanchu** [comment]
After digging in a bit, I agree with @neverfox . The "1052304032" in my print is the sequence number from the REST snapshot. While the snapshot was being requested, lots of websocket messages had arrived and were queued. Hence their sequence numbers are smaller and should be ignored when the continuous streaming kicks off.
