### ISSUE TITLE
Cancel All doesn't work as documented

### ISSUE THREAD

**Issue by exquest** [danpaquin/gdax-python#217]
According to the documentation you are supposed to run:  `auth_client.cancel_all(product='BTC-USD')` to cancel all orders for a specific product when in fact the command require you to run `auth_client.cancel_all(product_id='BTC-USD')`.

Not a huge deal but it is an error.

**Comment by TheFrostyboss** [comment]
I've submitted a pull request

**Comment by danpaquin** [comment]
This has been updated.
