### ISSUE TITLE
Is this a bug or bad vendor documentation?

### ISSUE THREAD

**Issue by ReedJessen** [danpaquin/GDAX-Python#22]
I am writing a new test module.  Specifically, I am currently working validating the responses to make sure there are no truncation errors by creating assertions like
```python
    def testProductTicker(self):
        results = self.publicClient.getProductTicker(product=TEST_PRODUCT_ID)

        trunc_error_message = "value has too few digits after decimal, possible truncation error"
        self.assertEqual(results['ask'][::-1].find('.'), 2, msg=trunc_error_message)
        self.assertEqual(results['bid'][::-1].find('.'), 2, msg=trunc_error_message)
        self.assertEqual(results['price'][::-1].find('.'), 8, msg=trunc_error_message)
        self.assertEqual(results['volume'][::-1].find('.'), 8, msg=trunc_error_message)
```

While working on `.getProducts()` I have come across an anomaly which I don't know if it's a bug or bad vendor documentation.

[GDAX documentation](https://docs.gdax.com/#products) indicates the response from `/products` will be:
```json
[
    {
        "id": "BTC-USD",
        "base_currency": "BTC",
        "quote_currency": "USD",
        "base_min_size": "0.01",
        "base_max_size": "10000.00",
        "quote_increment": "0.01"
    }
]
```
Notice that `"base_max_size"` has 2 places after the decimal point.  My test to verify that our responses also have two spaces after the decimal point is:
```python 
for result in results:
    self.assertEqual(result['base_max_size'][::-1].find('.'), 2, msg=trunc_error_message)
```
This test fails every time however because the actual response that `GDAX.PublicClient().getProducts()` returns looks like this:
```json
[{
	"quote_currency": "GBP",
	"base_max_size": "10000",
	"id": "BTC-GBP",
	"base_currency": "BTC",
	"quote_increment": "0.01",
	"base_min_size": "0.01",
	"display_name": "BTC/GBP"
}]
```
Notice that `"base_max_size"` has no decimal point or values after it as if it was truncated.

Do you think the GDAX documentation is wrong and this response is correct?  In this case, I should ditch my truncation test for `"base_max_size"`.  Alternatively, is `GDAX.PublicClient().getProducts()` buggy here and my test is working correctly?

**Comment by ReedJessen** [comment]
This might be a larger issue.  The tests intermittently return 2, 1, or 0 decimal places in some instances, and 7 or 8 decimal places in other cases. What I think might be happening is that somewhere along the pipeline, python is inferring that they are floats and then truncating the numbers, then they are explicitly turned back into strings later on.  Very weird.

Thoughts anyone?

**Comment by danpaquin** [comment]
Hey Reed,

I'm on mobile so I'll update this when I'm able to check, but all responses return the raw JSON from the API. The method does not parse any values.  I would remove this check for now but keep this open for future review.

**Comment by danpaquin** [comment]
@ReedJessen Any progress on this? I will be adding support for additional endpoints in the next few weeks.
