### ISSUE TITLE
How to withdraw from gdax wallet to another wallet?

### ISSUE THREAD

**Issue by ronenshohat** [danpaquin/gdax-python#220]
Hi,

I have an LTC wallet that I'm looking to withdraw LTC from my GDAX account. Is there a way to do this on the API? Thanks for the help

**Comment by mattpearson** [comment]
This method appears to do it. However, when I execute it, I get an error.  Despite passing the currency, such as 'LTC', I get an error saying "{u'message': u'currency is required'}"...

https://github.com/danpaquin/gdax-python/blob/master/gdax/authenticated_client.py#L259

**Comment by mattpearson** [comment]
Any updates on this -- no matter the capitalization of currency or whether amount is a string or a number, the crypto_withdraw method always returns "currency is required". I have tried both LTC and ETH. Has @danpaquin successfully utilized this method? 

Thank you!

**Comment by acontry** [comment]
The Python library looks like it implements the [crypto withdrawal API](https://docs.gdax.com/#crypto) correctly. From their example the currency should be "LTC", "BTC", etc. Does any of this change the response? If not, they might have an issue on their end with this endpoint and a ticket should be raised with GDAX.

**Comment by alimcmaster1** [comment]
Try hitting the rest endpoint directly as documented on Gdax does that work for you?

**Comment by ronenshohat** [comment]
how do I hit the rest endpoint directly? I tried the crypto_withdraw function but got the same error mentioned above

**Comment by ronenshohat** [comment]
Any updates on this? Anyone else get this to work? Appreciate the help.

**Comment by zgdaf** [comment]
is your question on how to hit gdax endpoint directly?  If so try using postman.

**Comment by ronenshohat** [comment]
My question is to why the withdraw function of the API doesn't work- has anyone got it to work/researched why it isn't working? What would I try to do with postman?

**Comment by mattpearson** [comment]
I couldn't get the withdraw function from the API to work either, so I ended up going to the GDAX endpoint directly. Here is sample code that shows how to do it.

https://github.com/mattpearson/Misc/blob/master/GDAX%20Withdraw%20Crypto.py

**Comment by danpaquin** [comment]
This has been resolved via #207.
