### ISSUE TITLE
Not quite sure how to place market orders

### ISSUE THREAD

**Issue by madsthaks** [danpaquin/gdax-python#224]
The syntax given to place limit orders is straight forward:

```
# Buy 0.01 BTC @ 100 USD
auth_client.buy(price='100.00', #USD
               size='0.01', #BTC
               product_id='BTC-USD')
```

This works well but I'm not sure how to place market orders. I'd ideally want to provide some dollar amount and the `product_id`. 

Any help would be much appreciated.

**Comment by smalbadger** [comment]
auth_client.buy(size='0.01', product_id="BTC-USD", type="market")

with a market buy, you don't get to decide what price you actually trade at. It just buys at whatever price someone is trying to sell at.
