### ISSUE TITLE
getProductHistoricRates not responding to start=, end=

### ISSUE THREAD

**Issue by plengkeek** [danpaquin/GDAX-Python#23]
When looking at the official documentation of GDAX, the getProductHistoricRates takes arguments start, end and granularity. However only the latter one seems to work. Whenever using start or end it just returns the latest result from the server. 

Any thoughts to why?

**Comment by Gilgamesh22** [comment]
note that the start and end parameters are in ISO 8601. hence YYYY-MM-DD for example may 4 2017 is 2017-05-04. 
here is a link to explain https://en.wikipedia.org/wiki/ISO_8601 
here is some sample code PC.getProductHistoricRates(granularity=1000 , start='2017-05-04', end='2017-05-05' )

**Comment by plengkeek** [comment]
My bad it very clearly states ISO 8601 in the documentation.
