### ISSUE TITLE
"received" type

### ISSUE THREAD

**Issue by illera88** [danpaquin/gdax-python#232]
Hi,
I'm using the websockets and I see there is a message type `received` that is not handled by the `on_message` [order book](https://github.com/danpaquin/gdax-python/blob/master/gdax/order_book.py#L74).

where can I see all the different types that I can receive using websockets?

Cheers

**Comment by smalbadger** [comment]
Here is the official documentation for the GDAX API. The link should take you to the websocket section of the document.
https://docs.gdax.com/#websocket-feed

**Comment by danpaquin** [comment]
While there is improvement to be made in this, I will close this out as it appears to be a concern of how the orderbook works rather than an issue with the logic.

From the [GDAX documentation](https://docs.gdax.com/#the-code-classprettyprintfullcode-channel) listed by badger:

> The **received** message does not indicate a resting order on the order book. It simply indicates a new incoming order which as been accepted by the matching engine for processing.
