### ISSUE TITLE
order_book.py and time.sleep(10)

### ISSUE THREAD

**Issue by soukainahamidi** [danpaquin/gdax-python#238]
Hello,

I was wondering why do we need: time.sleep(10) (line:291 in order_book.py)?

Thanks!

**Comment by mcardillo55** [comment]
When orderbook is initialized, it fetches the current order book from gdax first [here](https://github.com/danpaquin/gdax-python/blob/master/gdax/order_book.py#L42), then it feeds all these open orders into the rbtree. These 2 operations take a little time, and the orderbook will not work correctly until they complete.
