### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by treeguard** [danpaquin/gdax-python#240]
I don't think this is the python library issue. I posted here to see if anyone has the same problem. I used the code example from API doc, but got errors, I have tried to create three APIs.

import json, hmac, hashlib, time, requests, base64
from requests.auth import AuthBase

# Create custom authentication for Exchange
class CoinbaseExchangeAuth(AuthBase):
    def __init__(self, api_key, secret_key, passphrase):
        self.api_key = api_key
        self.secret_key = secret_key
        self.passphrase = passphrase

    def __call__(self, request):
        timestamp = str(time.time())
        message = timestamp + request.method + request.path_url + (request.body or '')
        hmac_key = base64.b64decode(self.secret_key)
        signature = hmac.new(hmac_key, message, hashlib.sha256)
        signature_b64 = signature.digest().encode('base64').rstrip('\n')

        request.headers.update({
            'CB-ACCESS-SIGN': signature_b64,
            'CB-ACCESS-TIMESTAMP': timestamp,
            'CB-ACCESS-KEY': self.api_key,
            'CB-ACCESS-PASSPHRASE': self.passphrase,
            'Content-Type': 'application/json'
        })
        return request

api_url = 'https://api.gdax.com/'
API_KEY = ""
API_SECRET = ""
API_PASS = ""
auth = CoinbaseExchangeAuth(API_KEY, API_SECRET, API_PASS)

if __name__ == "__main__":
    # Get accounts
    r = requests.get(api_url + 'accounts', auth=auth)
    print r.json()

**Comment by danpaquin** [comment]
I would double check you're using the right keys in the right areas.  for example, the difference between the secret and passphrase are subtle when you're creating the API Key.  If this continues to be an issue, please reach out to a contributor directly.
