### ISSUE TITLE
Is there any way to print or store the real time order book locally using websocket?

### ISSUE THREAD

**Issue by Diptayan1995** [danpaquin/gdax-python#241]
I am using this code : 
import gdax, time
order_book = gdax.OrderBook(product_id='ETH-USD')
order_book.start()
print str(order_book.get_current_ticker()))
time.sleep(10)
order_book.close()

And it returns 'None' . 

I've installed gdax library from this github repository . So i want to know if there is any way to print or store the real time order book locally using websocket .

**Comment by mcardillo55** [comment]
What you are doing should work, the issue is that the OrderBook object must fetch all open orders which takes a few seconds. OrderBook.get_current_ticker() will return None until it is populated. Try moving the sleep(10) before the print and you should have better results.
