### ISSUE TITLE
auth_client.cancel_all() does not seem to work; neither does auth_client.get_orders(product_id = 'ETH-USD')

### ISSUE THREAD

**Issue by fmxiao** [danpaquin/gdax-python#246]
I have solved the problem by downloading the gdax package from github directly. Thanks 

I tried: 
    auth_client.cancel_all() 
It gave an error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/gdax/authenticated_client.py", line 92, in cancel_all
    data=json.dumps({'product_id': product or self.product_id}), auth=self.auth)
AttributeError: 'AuthenticatedClient' object has no attribute 'product_id'

I also tried:
    auth_client.cancel_all(product_id = 'ETH-USD'), 
It gave an error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cancel_all() got an unexpected keyword argument 'product_id'

I then tried
    auth_client.get_orders(product_id = 'ETH-USD'),
this does not work either. It gave:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_orders() got an unexpected keyword argument 'product_id'

I might have simply missed something. Please help out. Thanks.

**Comment by bpross** [comment]
I ran into this as well, and was able to fix it. I was using `gdax==1.0.6` and installing it through `pip`. It seems like that version of the code is old, and does not match the documentation in the README. If you install from the git repo `pip install /path/to/gdax/git/repo` it should fix it.

Cheers.
