### ISSUE TITLE
How to get list of open positions?

### ISSUE THREAD

**Issue by vgoklani** [danpaquin/gdax-python#251]
How do I get a list of open positions via the API? That is, suppose I BUY two BTC-USD at (say) $9500 and $9600, with sizes of 0.6 and 1.2 respectively. How would I a list of these open positions? The fill method gets me the full history, but it doesn't tell me which positions are still open. I need a quick way of making sure my app is in sync with the exchange... Thanks

**Comment by BattlestarPegasus** [comment]
Have you tried to just create a list/pandas dataframe and append price with size as open positions.  Just subtract when you sell and you can calculate the difference.  You can also call gdax and see what amount your invested in for each currency pair.

**Comment by Jaewan-Yun** [comment]
You would need to get the account ID of your BTC-USD account, and send that information to the argument of method

`get_account_holds(account_id)`

It will return the amount of either BTC or USD you have on hold on this account. The hold will be there because you have placed buy and/or sell orders.

**Comment by vgoklani** [comment]
@BattlestarPegasus I want to synchronize it; suppose for example I have to manually close an order via the gdax web app, how would my application know?

@Jaewan-Yun 1. listing orders simply lists *open* orders, not positions. 
2. get account holds doesn't tell me the amount i paid for the BTC, per position, etc.

**Comment by mcardillo55** [comment]
AFAIK GDAX doesn't keep track of that detailed of information (amount paid per currently open position). I suppose you could get your wallet balances via `get_accounts()` and do some kind of manual bookkeeping though with `get_fills()` though.
