### ISSUE TITLE
buy order not buying

### ISSUE THREAD

**Issue by tsgrau** [danpaquin/gdax-python#254]
My code will process without any errors, that I can see at least, but my order requests do not seem to be going thru.  When I look at my GDAX account, there are not any open orders ( and it has not been filled either).

I am testing this in the sandbox, and it works great, no problems, but when I go to my real account, nothing happens.  I also ran the get orders command for my real account, and it returns empty.

I am testing this with my real account by requesting an order to buy at a very low price, so I know it will not get filled.

This is my code...

def post_buy(qty,product,price_1):
    """buy $xx worth of product"""
    print('Qty = ' + str(qty) + ' at $' + str(price_1) + ' for product = ' + product)
    auth_client.buy(price=price_1, size=qty, product_id = product)
    return qty 

I know my keys are ok, because i have another function defined to cancel all orders, and that works just fine, after I manually create orders in GDAX.

my "print" line above produces this result...

Qty = 0.20002499 at $200 for product = ETH-USD

**Comment by Jaewan-Yun** [comment]
Do you have all the necessary permissions granted for the API in your GDAX account settings?

**Comment by tsgrau** [comment]
I checked my permissions and my key settings are for view, trade, & manage.  That seems like I should be good.  The only other permission is for transfers.

**Comment by tsgrau** [comment]
Correction, I did not have the trade setting in my permissions.  I went back and created a new key with the trade setting included, and now it works.  Thanks, but do I feel pretty dumb!  
Many good fortunes my friend!

**Comment by Jaewan-Yun** [comment]
Great! Glad to help.
