### ISSUE TITLE
Orderbook fails to subscribe

### ISSUE THREAD

**Issue by SorenJ89** [danpaquin/gdax-python#257]
I have been running the same code for a month without errors, but suddenly it won't start.
I'm receiving the following message (in orderbook's on_message):

> 'type': 'error', 'reason': 'You need to specify at least one product ID for channel heartbeat', 'message': 'Failed to unsubscribe'

which is weird since i specify the product id when i create the orderbook

> OrderBookConsole(product_id='BTC-EUR')

Does anyone have suggestions to how this can be fixed?

**Comment by gsmadi** [comment]
Fix is quite easy just do, `sequence = message.get('sequence', -1)` in line 64 of `gdax/order_book.py` in `development` branch.

An assumption is the first message will always contain the sequence number. Seems this recently changed.

Here is the PR for the fix [#258](https://github.com/danpaquin/gdax-python/pull/258).

**Comment by mcardillo55** [comment]
I think this may be related to #262 as well. Can you update your repo and try again?
