### ISSUE TITLE
import GDAX fails

### ISSUE THREAD

**Issue by htso** [danpaquin/GDAX-Python#26]
This was working a wk ago, but now fails with this error, any idea?  

/usr/local/lib/python2.7/dist-packages/GDAX/WebsocketClient.py in <module>()
     10 import time
     11 from threading import Thread
---> 12 from websocket import create_connection
     13 
     14 

ImportError: cannot import name create_connection

**Comment by danpaquin** [comment]
Hi htso, this seems to be an issue with your websocket implementation. Could you provide more details on the packages/version you have installed in your instance of Python?

**Comment by htso** [comment]
Hi, I must have accidentally damaged websocket. Here is what i see under /python2.7/dist-packages 

/websocket
/websocket-0.2.1-dist-info
/websocket_client-0.40.0.egg-info

Inside /websocket, I open __init__.py and i see version = '0.2.1'

However, and this' what made me concluded something's wrong, when I list all the packages from inside python 

>>> help('modules')

I don't see websocket anywhere. 

Thanks in advance for the help.

Horace

**Comment by htso** [comment]
i have more discovery. Since error says websocket-client is missing, i thought i may just install that with

`sudo pip install websocket-client`

What i got is something bordering on an error, so pls tell me what's wrong,

/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by danpaquin** [comment]
After reviewing your errors, I found the following in the readme of websocket-client:

> SNI support is available for Python 2.7.9+ and 3.2+. It will be enabled automatically whenever possible.

This appears to be an environmental issue, but I will let you know if I come across this issue myself. Please continue to provide environment insight if you would like my two cents moving forward :)

**Comment by julyanserra** [comment]
@htso did you figure this issue out? I am having the exact same problem.

**Comment by htso** [comment]
Hi Julian, no I did not. But let me tell you how I eventually resolved
this. I tried GDAX on my previous ubuntu box and it went dead (for reason
unrelated to crypto activity). Then I installed GDAX on a Windows 10
machine and it works just fine, though I haven't used much of it lately.

H

**Comment by scoupafi** [comment]
This problem is probably caused from the creation of a websocket.py file on the working directory.
Check if that's the case.

**Comment by nirflanker** [comment]
I too faced the same issue. It was definitely due to a file called `websocket.py` in the same working directory. Getting rid of it fixed the issue
