### ISSUE TITLE
Removal of "self.ws.send(json.dumps(sub_params))" on line 76  in websocket_client.py causes problem

### ISSUE THREAD

**Issue by BattlestarPegasus** [danpaquin/gdax-python#263]
{
    "message": "Failed to unsubscribe",
    "reason": "You need to specify at least one product ID for channel heartbeat",
    "type": "error"
}

I added it back in and no longer had this message error

**Comment by Nicholas-Schaub** [comment]
I am having the same issue. I will look to confirm this.

**Comment by Nicholas-Schaub** [comment]
Reading through the documentation, it doesn't appear as though there is any need for the following lines of code starting on line 77:

        if self.type == "heartbeat":
            sub_params = {"type": "heartbeat", "on": True}
        else:
            sub_params = {"type": "heartbeat", "on": False}

I don't see the need for the "on" argument in the API:
https://docs.gdax.com/#the-code-classprettyprintheartbeatcode-channel

I deleted the above lines and things seem to work flawlessly. If someone else could confirm...

**Comment by Nicholas-Schaub** [comment]
I went to go submit a pull request, but it looks like one has already been submitted for this in #262

**Comment by mcardillo55** [comment]
#262 Merged, this should be resolved.
