### ISSUE TITLE
Pull Transaction Hash To Follow Withdrawals to Confirmed Deposits

### ISSUE THREAD

**Issue by beeflowers287** [danpaquin/gdax-python#266]
When you call the following withdrawal endpoint 'withdrawals/crypto' you will get a transfer id in the response. That is specific to coinbase/gdax.

My question is, once you have the transfer id how can you get its details? (E.g. Estimated Payout and Transaction Hash , etc.)

Once a withdrawal occurs I could use the transaction hash to follow its confirmations on the blockchain, if it has x or more confirmations I can assume the withdrawal is complete. However I am wondering how to pull the transaction hash with which I could query various block explorers to ascertain confirmations. So far I only have the transfer id, what is needed is the transaction hash. Any ideas as to how to get that from GDAX api?

**Comment by danpaquin** [comment]
Hello @beeflowers287 -- you do not need to pull transaction hash from GDAX.  I see two scenario's here:

1. You withdraw to your Coinbase/GDAX account and use the correct endpoints to monitor balance changes.
2. You withdraw to a crypto address **which you supplied**, so you can watch the balance change through the blockchain.

Please email me if this continues to challenge you.

**Comment by beeflowers287** [comment]
Emailed your gmail acct.
