### ISSUE TITLE
candle number in get_product_historic_rates

### ISSUE THREAD

**Issue by alex0527** [danpaquin/gdax-python#269]
Hi,

On gdax api document, it says" If data points are readily available, your response may contain as many as 350 candles and some of those candles may precede your declared start value." However, recently I noticed the function only retrieved ~300 candles, does anyone know the reason? thanks.

**Comment by TheKeyboardKowboy** [comment]
"as many as", so there is no guarantee they will respond with 350 candles.

**Comment by danpaquin** [comment]
this seems to be resolved. please open a new issue if this persists.
