### ISSUE TITLE
Minimum buy via api is higher than that of gdax

### ISSUE THREAD

**Issue by devneal** [danpaquin/gdax-python#281]
Using the sandbox website, the following buy fails:
```
auth_client.buy(price='9145',
                size='0.001',
                product_id='BTC-USD')
```
however, this one succeeds:
```
auth_client.buy(price='9145',
                size='0.01',
                product_id='BTC-USD')
```
It seems like the api is enforcing a higher minimum than 0.001 BTC, [which is the minimum for gdax](https://support.gdax.com/customer/portal/articles/2725970-trading-rules).

**Comment by mcardillo55** [comment]
The sandbox may be running outdated versions. Regardless, sounds like a GDAX API issue. Does the buy failure relate to gdax-python? Or does it return a failure from the API?

**Comment by devneal** [comment]
Turns out it's a problem on the gdax side. Closing.
