### ISSUE TITLE
Stop Orders?

### ISSUE THREAD

**Issue by jscnet68** [danpaquin/gdax-python#293]
How to place a STOP order?   gdax_client.sell() doesn't like the 'stop' or 'stop_price' keywords.

errors:
sell() got an unexpected keyword argument 'stop'
sell() got an unexpected keyword argument 'stop_price'

Please provide a BUY and SELL example, with a limit price too.  Thanks.

**Comment by nalepae** [comment]
Hello, 

Without limit price:

The equivalent of following picture
![image](https://user-images.githubusercontent.com/4943830/39386664-fc991b68-4a75-11e8-94a7-e60a19b2bff2.png)

is the following code:

`auth_client.buy(stop_price="9000", product_id="BTC-EUR", stop_type="entry", type="market", funds="1000")`

The equivalent of following picture
![image](https://user-images.githubusercontent.com/4943830/39386699-1a243802-4a76-11e8-8a6c-ead193fbbb5c.png)

is the following code:

`auth_client.sell(stop_price="6000", product_id="BTC-EUR", stop="loss", type="market", size="0.02")`
