### ISSUE TITLE
https://api.pro.coinbase.com/

### ISSUE THREAD

**Issue by seomradubh** [danpaquin/gdax-python#306]
Hi there, I just started using your code, but got the email about coinbase pro in recently.

Will there be many changes to the code, or is it simply a matter of using the new api address instead of the gdax one used previously? 

I had an issue with auth client last night so said I would wait to see if the pro api had broken something, thanks a lot!
SD

**Comment by danpaquin** [comment]
This will be a priority to convert over to the new api endpoints, so please post updates here when GDAX is fully transitioned.

**Comment by slayorktc** [comment]
Should I open a new ticket but I am confused how to place a Market Order. I see you have a buy and sell but I assume those setting a limit order?

**Comment by slayorktc** [comment]
Awesome work! Where is your BTC/ETH donation address? Didn't see it on the readme. Finished my little script. Very easy with your work! Thanks!

**Comment by danpaquin** [comment]
We merged the url change! Please reach out via email if you're interested in donating, thanks!
