### ISSUE TITLE
websocket orderbook not displaying any data.

### ISSUE THREAD

**Issue by cyzanfar** [danpaquin/gdax-python#32]
Hey,

I'm trying to run the WebSocket orderbook example `python OrderBook.py`
I only get this back:
```
-- Subscribed! --


-- Socket Closed --
```

and nothing else. 

thanks!

**Comment by danpaquin** [comment]
Hi @cyzanfar, thank's for sharing this question.  If you take a look at GDAX/OrderBook.py, on line 212 you will see the following which will explain why you are experiencing this behavior.  The order book is being initialized via the websocket stream and then closed 10 seconds later.  **In order to improve this default behavior, what where you expecting for the result?**

```python
if __name__ == '__main__':
    import time
    order_book = OrderBook()
    order_book.start()
    time.sleep(10)
    order_book.close()
```

**Comment by cyzanfar** [comment]
Hi @danpaquin. When calling OrderBook i'd expect to get back the actual live stream orderbook with the asks, bids and amount. Similar to the response we get from the REST endpoint for orderbook. Isn't that the expected output ?

**Comment by danpaquin** [comment]
@cyzanfar You would like a console print out of this information? This can be done with the current OrderBook methods, but has yet to beimplemented. If you would like to contribute to the default behavior I will merge any pull requests regarding this. If not, I will put it on my to-do list.

Thanks,
Dan

**Comment by cyzanfar** [comment]
Yes correct a console print out would be great. I'' take a look and try to get it working then submit a PR.
Quick question. Where you able to imlement the logic described in the orderbook websocket section on the GDAX api doc ?

```

**Comment by danpaquin** [comment]
Yes! I was not the one to implement it, but the logic is nearly identical to the official client for Node. Please let us know if you happen to find issues with the real-time logic so we can fix ASAP.

Thanks,
Dan

**Comment by cyzanfar** [comment]
Proposed [PR](https://github.com/danpaquin/GDAX-Python/pull/33) for this enhancement.
👍

**Comment by PaulMest** [comment]
Looks like the PR mentioned was closed without getting merged. Here is an alternative implementation: #75. This subclasses `OrderBook` into `OrderBookConsole`. This way there won't be any performance impact for others who want to subclass directly from `OrderBook` and not waste any cycles calculating the changes to bid-ask spread and logging to the console.

**Comment by danpaquin** [comment]
Thanks Paul, the initial PR had a few unresolved issues for a month so I closed it out.

**Comment by PaulMest** [comment]
I have had this code locally for a while and found it pretty useful. So feel free to make comments on my PR and I'll get them resolved within a few days.

**Comment by danpaquin** [comment]
Awesome! I'm on mobile but I'll commit changes when I have a chance to experiment with the code.

Thanks again.

**Comment by cyzanfar** [comment]
Good idea!
