### ISSUE TITLE
AttributeError: 'AuthenticatedClient' object has no attribute 'cryptoWithdraw'

### ISSUE THREAD

**Issue by rjb25** [danpaquin/GDAX-Python#34]
I am getting the above error:
```
AttributeError: 'AuthenticatedClient' object has no attribute 'cryptoWithdraw'
```
I am wondering if this is on my end or yours. It seems to be a problem on your end?
I am calling [this method](https://github.com/danpaquin/GDAX-Python/blob/master/GDAX/AuthenticatedClient.py#L224) from `AuthenticatedClient`:
```
def cryptoWithdraw(self, amount="", currency="", crypto_address=""):
        payload = {
            "amount": amount,
            "currency": currency,
            "crypto_address": crypto_address
        }
        r = requests.post(self.url + "/withdrawals/crypto", data=json.dumps(payload), auth=self.auth)
        # r.raise_for_status()
        return r.json()
```
Methods such as `buy` are working for me.

**Comment by rjb25** [comment]
Might help to note I am using pip3

**Comment by rjb25** [comment]
No hurry on this, I just hard coded `cryptoWithdraw` into my script. It might be nice for others in the future if this was handled.

**Comment by danpaquin** [comment]
Hey @rjb25, thank you for sharing.

Are you using the most current version of GDAX through PyPI? If so, I have yet to update the project with cryptoWithdraw as we are busy with other implementations.  I will be sure to update the PyPI project with the current functions.  My goal is to have a V1 out in the next few months that is more consistent (e.g. buy/sell only accept JSON).

**Comment by danpaquin** [comment]
Closing this out with the release of v0.3 -- enjoy!
