### ISSUE TITLE
Misplacement of % in the basic myWebsocketClient in WebsocketClient

### ISSUE THREAD

**Issue by pretzel729** [danpaquin/GDAX-Python#35]
In the myWebsocketClient template class in GDAX.WebsocketClient:

`print ("\nMessageCount =", "%i \n") % wsClient.MessageCount`
The above line causes the type error below.
> TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'

It should be:
`print ("\nMessageCount =", "%i \n" % wsClient.MessageCount)`

**Comment by danpaquin** [comment]
Thanks for sharing, this happened to be a typo to be honest.  In my ad hoc test scripts, I didn't have this issue.  I will be sure to watch out for this as Python3 becomes the primary language.
