### ISSUE TITLE
Pythonic Conventions, PEP 8, & Features

### ISSUE THREAD

**Issue by Jigsaw-Jams** [danpaquin/GDAX-Python#37]
Hey @danpaquin are you guys open to me submitting a PR to modify some things to make this package more Pythonic and compliant with PEP 8?

 I have a bunch of things I would like to change and work on but here are a few:
* Function names should be all lowercase words seperated by underscores (so `PublicClient.get_products()` instead of `PublicClient.getProducts()`
* Add [docstrings](https://www.python.org/dev/peps/pep-0257/) for modules, classes, and methods.
* Package name should be lowercase. 

------

I also want to help develop additional features/endpoints if you guys have anything in particular you want implemented/fixed let me know and I will start working on it.

**Comment by danpaquin** [comment]
Sure! This these changes won't be backwards compatible, please hold on the fork until 5/27. I will be pushing the current state to pypi this evening as the final v0. I expect your PR to be the initial v1 of this project, thanks for the idea!

**Comment by danpaquin** [comment]
v0.3 released

@Jigsaw-Jams If you would like, please begin to make any changes, even if they are not backwards compatible and create a PR!

**Comment by acontry** [comment]
I just issued PR #52 to close out this issue (except for docstrings).

I'm also looking to keep cleaning up the code and getting some unit tests going in the near future.

**Comment by Jigsaw-Jams** [comment]
Hey, sorry I never got to this. Thanks for taking care of it @acontry!

Closing this issue due to PR #52  Will open a new one for docstrings.
