### ISSUE TITLE
Version 0.3 from PyPi not working

### ISSUE THREAD

**Issue by fracek** [danpaquin/GDAX-Python#38]
I just installed version 0.3 from PyPi and it's not working because it includes a git conflict in `WebsocketClient.py`

```
if __name__ == "__main__":
    import GDAX, time
    class myWebsocketClient(GDAX.WebsocketClient):
        def onOpen(self):
            self.url = "wss://ws-feed.gdax.com/"
            self.products = ["BTC-USD", "ETH-USD"]
            self.MessageCount = 0
            print ("Lets count the messages!")

        def onMessage(self, msg):
            print ("Message type:", msg["type"], "\t@ %.3f" % float(msg["price"
]))
            self.MessageCount += 1

        def onClose(self):
            print ("-- Goodbye! --")

    wsClient = myWebsocketClient()
    wsClient.start()
    print(wsClient.url, wsClient.products)
    # Do some logic with the data
    while (wsClient.MessageCount < 500):
<<<<<<< HEAD
        print ("\nMessageCount =", "%i \n" % wsClient.MessageCount)
=======
        print("\nMessageCount =", "%i \n" % wsClient.MessageCount)
>>>>>>> e5d2bb8d930db1ddf64ab446467845a41f0ab5cd
        time.sleep(1)
    wsClient.close()
```

I'm using Python 3.5 with a freshly created virtualenv.

**Comment by ekerstein** [comment]
I just installed and got this error:

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/GDAX/WebsocketClient.py", line 105
<<<<<<< HEAD
^ 
IndentationError: expected an indentent block

**Comment by trecchia** [comment]
I'm getting this too after updating the package to the latest version

**Comment by danpaquin** [comment]
Yes, this has been fixed and uploaded to PIP. I apologize for this, but I would highly recommending creating your own class that inherits websocket client for improved flexibility.
