### ISSUE TITLE
Binary floating point arithmetic

### ISSUE THREAD

**Issue by bryankaplan** [danpaquin/GDAX-Python#40]
OrderBook.py coerces numeric strings to floats in a variety of places. This is a problem because [it changes the numbers](https://docs.python.org/3.6/tutorial/floatingpoint.html). A better solution would be better to use [decimal](https://docs.python.org/3.6/library/decimal.html).

I would issue a PR to make this change myself, but OrderBook.py exists in the master branch, not in the development branch.

**Comment by danpaquin** [comment]
Hi bryankaplan -- thank you for clarifying.  We have yet to truly use the development branch effectively, please make your commits to the master branch.

**Comment by bryankaplan** [comment]
Closing this issue, as #41 was merged.
