### ISSUE TITLE
AttributeError: 'map' object has no attribute 'index'

### ISSUE THREAD

**Issue by bryankaplan** [danpaquin/gdax-python#55]
In OrderBook.py, there is a line that says:

    index = map(itemgetter('id'), bids).index(order['order_id'])

and there is another line that does the same thing for asks.

How did this ever work? `map` objects do not have `index` attributes.
I recently received this stack trace:

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/usr/lib64/python3.5/threading.py", line 862, in run
        self._target(*self._args, **self._kwargs)
      File "/home/ec2-user/src/gdax/venv/src/gdax/GDAX/WebsocketClient.py", line 28, in _go
        self._listen()
      File "/home/ec2-user/src/gdax/venv/src/gdax/GDAX/WebsocketClient.py", line 59, in _listen
        self.onMessage(msg)
      File "/home/ec2-user/src/gdax/orderbook.py", line 10, in onMessage
        super().onMessage(message)
      File "/home/ec2-user/src/gdax/venv/src/gdax/GDAX/OrderBook.py", line 62, in onMessage
        self.change(message)
      File "/home/ec2-user/src/gdax/venv/src/gdax/GDAX/OrderBook.py", line 149, in change
        index = map(itemgetter('id'), bids).index(order['order_id'])
    AttributeError: 'map' object has no attribute 'index'

It looks like maybe you meant to coerce the map into a `list` before
asking for `index`, But I'm really not sure.

To be honest, I find these lines to be a pretty confusing way of doing
this. They could use some explanatory comments along with the fix.

**Comment by acontry** [comment]
Pycharms's static analysis flagged this for me, but I couldn't understand the context so punted on it instead of addressing it in PR 52. OrderBook.py needs some love overall, but are you interested in a patch in the meantime?

**Comment by bryankaplan** [comment]
@acontry As much as I _think_ wrapping `map` in `list` would fix it, I'm not going to issue a PR to fix code I don't fully understand.

**Comment by danpaquin** [comment]
Pulling @davidcaseria in to review.

**Comment by bryankaplan** [comment]
I experienced this error without having updated to the PEP-8 refactor.

**Comment by uzbit** [comment]
I have a suggested fix in this branch: 
https://github.com/uzbit/GDAX-Python/tree/fix_AttributeError

Simply switch to list comprehension.

**Comment by bryankaplan** [comment]
@uzbit Thank you. `itemgetter` might be a builtin, but your code looks a lot more pythonic. It's more clear, and it looks like it works. Could you please issue a PR?

**Comment by bryankaplan** [comment]
Oh, and please remove [line 7](https://github.com/uzbit/GDAX-Python/blob/9e8a97232e70b74a6c928f51ab0bd402131d7454/gdax/order_book.py#L7) in that PR.

**Comment by PaulMest** [comment]
I've also fixed this issue and others, but didn't use the list comprehension syntax. Take a look at #79. Happy to use list comprehension if that's preferable or rebase my changes after #78 is merged.
