### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by Jigsaw-Jams** [danpaquin/gdax-python#56]
Let's get some good documentation going by adding docstrings to this package. 

I'm thinking we could work with the format from [Google's Python Style Guide](https://google.github.io/styleguide/pyguide.html#Comments).
```
def Foo(bar):
    """Does something.

    Longer explanation of how doing something can be accomplished.

    Args:
       bar: An instance of something.

    Returns:
        Something of type SomeType.

    Raises:
        BarError: An error occurred during Foo.
    """
    pass
```

**Comment by acontry** [comment]
You read my mind - I'm already working on docstrings in this format. Will have a PR soon!

**Comment by Jigsaw-Jams** [comment]
If you are online right now, push what you've got to your fork and then we could split up what you've got left?

**Comment by acontry** [comment]
@Jigsaw-Jams I can push in a couple hours. I have completed docstrings for PublicClient so far. I'm in the process of refactoring AuthenticatedClient so was waiting for the function signatures to settle before writing docstrings, but if you did work there it would still be useful I think, just might have to make some minor changes down the road.

**Comment by Jigsaw-Jams** [comment]
@acontry Sounds good, I've started working on AuthenticatedClient

**Comment by acontry** [comment]
@Jigsaw-Jams PublicClient changes are pushed to my fork for your reference. My strategy was to copy all the info from the API spec into the docstrings, so the user hopefully doesn't need to reference an outside source when using this package.

**Comment by Jigsaw-Jams** [comment]
@acontry I'm about halfway through AuthenticatedClient. I'm leaving out docstrings for a few methods that I think we will eventually factor out like the pagination ones.

**Comment by danpaquin** [comment]
Docstrings have been added to the PublicClient from #61. I will leave this open until Docstrings are complete across the entire project.

Thanks!
