### ISSUE TITLE
Inconsistence in variable naming

### ISSUE THREAD

**Issue by bianjiang** [danpaquin/GDAX-Python#57]
e.g., 

productId vs. product_id
orderId vs. order_id

A lot of places in the order are without the '_', while the GDAX api parameters are all with the underscore.  This is somewhat confusing, especially the recent changes on the buy and sell function that takes raw GDAX api parameters.

**Comment by danpaquin** [comment]
Agreed! This has been updated in PR #52 thanks to @acontry

**Comment by bianjiang** [comment]
Great, thanks!

**Comment by acontry** [comment]
I'm looking to implement more changes to clean up the API in the near future FYI. buy and sell need some work to make their usage clear.

**Comment by danpaquin** [comment]
Agreed. Thanks to everyone for your support. I'm closing this issue out.
