### ISSUE TITLE
Version 0.4

### ISSUE THREAD

**Issue by bryankaplan** [danpaquin/GDAX-Python#63]
Recent changes have led to a situation where documentation is completely incorrect for v0.3. Because PRs are being merged into master, anyone who comes along wanting to give this thing a try is going to be frustrated. For that reason, it's important to ship v0.4 sometime very soon. When we do, let's start targeting PRs at version branches.

**Comment by danpaquin** [comment]
Understood. Outdated documentation is better than outdated code. I'll get this pushed to PyPI within 48 hours and cleanup the branches.

**Comment by danpaquin** [comment]
Thanks for this.  Version 1.0 has been released released into PyPI. Due to non-backwards compatibility, we have released a new version.

**Comment by acontry** [comment]
@danpaquin thanks for the cleanup and release! Can we get a new branch (something like branch-1.1) to make PRs against?
