### ISSUE TITLE
Buy & sell orders fail with "got an unexpected keyword argument"

### ISSUE THREAD

**Issue by alsobrsp** [danpaquin/GDAX-Python#68]
Thank you for the work you do on this package.

Successful
>>> auth_client.getAccounts()

Not successful
>>> auth_client.buy(price='2560.00', size='0.01', product_id='BTC-USD')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: buy() got an unexpected keyword argument 'price'
>>> auth_client.sell(price='2560', #USD
...                 size='0.0001', #BTC
...                 product_id='BTC-USD')
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
TypeError: sell() got an unexpected keyword argument 'price'

**Comment by acontry** [comment]
I'm assuming you installed GDAX via pip. The documentation here on Github currently doesn't match the syntax of the pypi release (we'll fix it - see #63 :)). 

The version you have expects a dictionary of parameters. To solve your problem today, try this:
```python
buy_params = {'price': '2560', 'size': '0.0001', 'product_id': 'BTC-USD', 'type': 'limit'}
auth_client.buy(buy_params)
```
Note that I added a `type` param to specify limit order (see the [GDAX API ref](https://docs.gdax.com/?python#place-a-new-order) for details on all the required params).

Also note, we're gonna clean up AuthenticatedClient (and especially how you place orders) very soon so stay tuned.

**Comment by alsobrsp** [comment]
Thanks, I'll check that out. I have also updated my dev env to the current git version and now I am getting an argument error. If I can't sort it out I'll open another ticket.

`>>> auth_client = gdax.AuthenticatedClient(key, b64secret, passphrase)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alsobrsp/syeather_docs/CryptoCurrency/Scripts/trade-env/src/gdax/gdax/authenticated_client.py", line 19, in __init__
    super(AuthenticatedClient, self).__init__(api_url, product_id)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given`

**Comment by acontry** [comment]
Some recent changes broke AuthenticatedClient. See PR #69 for the fix. It's only a single line change, so you can add it yourself easily!

**Comment by alsobrsp** [comment]
This is perfect. Thank you.
