### ISSUE TITLE
Paginate_orders() in authenticated_client.py does not pass auth

### ISSUE THREAD

**Issue by slowder** [danpaquin/GDAX-Python#71]
The second page comes back with `{u'message': u'CB-ACCESS-KEY header is required'}`.
The following works for my use case:
```diff
     def paginate_orders(self, result, after):
-        r = requests.get(self.url + '/orders?after={}'.format(str(after)))
+        r = requests.get(self.url + '/orders?after={}'.format(str(after)), auth=self.auth)
```

**Comment by Jigsaw-Jams** [comment]
The auth seems to have been accidentally left out in this version. There is a major overhaul to `authenticated_client.py` coming soon which already addresses this issue and a ton of others. If you want, you can check out the changes [here](https://github.com/acontry/GDAX-Python/blob/authenticated-client-cleanup/gdax/authenticated_client.py).

If you need this method working now I would suggest cloning the repo and modifying that line locally, as the overhaul removes this method entirely and introduces a new system for pagination.

**Comment by danpaquin** [comment]
This has been addressed. Thank you for sharing.  Pagination is being reviewed moving forward.
