### ISSUE TITLE
'AuthenticatedClient' object has no attribute 'cancel_all'

### ISSUE THREAD

**Issue by BattlestarPegasus** [danpaquin/GDAX-Python#72]
Anyone else try to use this?

`authClient.cancel_all(product='LTC-USD')`

**Comment by BattlestarPegasus** [comment]
I just tried `authClient.cancelAll(product='LTC-USD')` and it worked just fine.  We should change the wiki from `auth_client.cancel_all(product='BTC-USD')` to `auth_client.cancelAll(product='BTC-USD')` so others know

**Comment by danpaquin** [comment]
I have recently updated PIP to match the current master branch. Please update and report back, thank you for reaching out!

`pip install gdax --upgrade`

**Comment by BattlestarPegasus** [comment]
Thanks all is good!  Sorry for getting back so late... Crazy past few days
