### ISSUE TITLE
buy() takes exactly 1 argument

### ISSUE THREAD

**Issue by AlexanderSchmedes** [danpaquin/GDAX-Python#76]
Hello,

I followed the example here [#68](https://github.com/danpaquin/GDAX-Python/issues/68) on how to use buy() currently.

Using 

> buy_params = {'price': '2560', 'size': '0.0001', 'product_id': 'BTC-USD', 'type': 'limit'}
auth_client.buy(buy_params)

I get the error 

> buy() takes exactly 1 argument (2 given)

**Comment by acontry** [comment]
The function signature for `buy` changed since that issue. Now it takes in keyword args, so you can do `auth_client.buy(**buy_params)` to unpack your dictionary into keyword arguments, or simply do: `auth_client.buy(price=2560, size=0.0001, product_id='BTC-USD', type='limit')`

**Comment by AlexanderSchmedes** [comment]
Ah, I see, thank you very much!
