### ISSUE TITLE
JSON Request Parameters' Syntax

### ISSUE THREAD

**Issue by danpaquin** [danpaquin/GDAX-Python#8]
# Which do you prefer?

Hello, I would like to open the discussion and get feedback on the syntax used to make requests with this client.  For the most part, functions accept named variables to package information for a given call.  

Below you will see the two methods used in this client for sending information to GDAX.  They are both very different approaches.  Ultimately, we should remain consistent in how a user makes requests to the API.  Which method should we adopt for every call?  I have included examples below so please make suggestions!

## *Method Variables*
```python
public.getProductHistoricRates(granularity='3000')
```

## *Raw JSON*
```python
params = {
'granularity': '3000'
}
public.getProductHistoricRates(params)
```

**Comment by danpaquin** [comment]
I have decided to allow both methods and will add a parser that prioritizes JSON requests for ultimate responsiveness.

The other approach will be great for intermediate use cases.

Comments and suggestions welcome!

**Comment by danpaquin** [comment]
After testing the code extensively, I have decided to implement the JSON Parse logic for ALL methods.  Any additional methods should allow both use-cases.  Comments and suggestions are welcome through development.

**Comment by danpaquin** [comment]
After reviewing Coinbase and GDAX Official API's, we are not going to allow for method variables as this makes the open source API harder to read and maintain.  **Moving forward. Only JSON params will be accepted.** This will be pushed to production soon.

**Comment by bryankaplan** [comment]
While [python dicts](https://docs.python.org/3.6/tutorial/datastructures.html#dictionaries) can look identical to [JSON](http://json.org/), the two are in fact very different things. Dicts are a type of python data structure with their own API; JSON is a string that conforms to a specification. Dicts are one of the building blocks of python. JSON is a common format usually used for sending data over the wire. There is no "raw JSON" in your example above. That is a dictionary.

To answer your question, the style you call "raw JSON" isn't very pythonic. The correct solution, IMHO, is to use [kwargs](https://pythontips.com/2013/08/04/args-and-kwargs-in-python-explained/). I have issued PR #39 to that end.

Thanks btw for writing this! It's useful.

**Comment by arpheno** [comment]
I support @bryankaplan 
`public.getProductHistoricRates(granularity='3000')`
is equivalent to

`params = {
'granularity': '3000'
}`
`public.getProductHistoricRates(**params)`

No need to support the syntax without stars.

**Comment by danpaquin** [comment]
Thank you for your feedback, all!  I am primarily self-taught on Python, so I appreciate your patience with my misunderstanding of some Python standards.  Closing this out.
