### ISSUE TITLE
AuthenticatedClient.get_orders() doesn't have status arguments

### ISSUE THREAD

**Issue by willguxy** [danpaquin/gdax-python#84]
Think that this functions returns orders with all status. If I only care about `open` orders, it would be more efficient to pull just open orders from gdax, right? So ideally, user can pass in the parameters as status

Please advise

**Comment by acontry** [comment]
Agreed! This is addressed in PR #81, which is currently pending.

**Comment by danpaquin** [comment]
Yes, this can be addressed client side for now, but we should allow for kwargs in this method.  Thank you for letting us know!
