### ISSUE TITLE
Deposit doesn't take JSON, requires currency.

### ISSUE THREAD

**Issue by ArnavSood** [danpaquin/gdax-python#87]
I'm seeing a few issues with the `AuthenticatedClient.deposit()` method. 

1. The docs say it takes its args in a Dict, but the method requires keywords.
2. Currency types aren't inferred; calling `deposit` with `amount` and `payment_method_id` returns `currency is required.`
3. Calling `deposit` on a `coinbase_account_id` instead of `payment_method_id` gives us an unexpected keyword error. 
4. Passing in the `payment_method_id` for my USD wallet yields: ```ValueError: No JSON object could be decoded```. Passing an ACH bank account yields a good deposit.

**Comment by danpaquin** [comment]
Thanks for this. I will add it to the TODO

**Comment by acontry** [comment]
1. Pending PR #81 addresses this.
2. `currency` field is required by the GDAX API. To infer this, the client would have to first make a call to `get_accounts`. The overall design for this python client leans towards being lightweight, so I don't think it would make sense to add this. 
3. There's a separate `coinbase_deposit` method - did you use that?
4. I haven't used `deposit` outside of the sandbox API for testing, so this one I'm not sure on. Is this also a Coinbase/GDAX thing?
