### ISSUE TITLE
Websocket closes

### ISSUE THREAD

**Issue by pauljherrera** [danpaquin/gdax-python#89]
Hi, 

When I use the websocket, it stops receiving data after three or four hours. It doesn't raise an error. It doesn't report "Socket Closed" or anything. It just stops receiving data. I don't know if this is an issue of the GDAX API or an issue of gdax-python.

**Comment by BattlestarPegasus** [comment]
Same here.  It just stops after a few hours of running.  I just automatically reset the websocket every 60 mins and it seems to be the only option right now

**Comment by mabounassif** [comment]
Same, I get the `No JSON object could be decoded` error.

**Comment by Londo-Mollari** [comment]
Battlestar, how do you close the stream and restart it in your code?  I'll have to do the same.  Thanks!

**Comment by acontry** [comment]
gdax-node includes a pinger in their websocket code to keep the connection alive:
```
// Set a 30 second ping to keep connection alive
self.pinger = setInterval(function() {
  self.socket.ping("keepalive");
}, 30000);
```
Just a hunch, but I bet adding a pinger would help.

**Comment by danpaquin** [comment]
Thanks @acontry -- I have added a pinger.  Please open a new issue if you continue to experience this.  It will be pushed to PyPI in the next few weeks.
