### ISSUE TITLE
Product historic data range

### ISSUE THREAD

**Issue by Algogator** [danpaquin/gdax-python#91]
Running 

```
hist = publicClient.get_product_historic_rates(
            'BTC-EUR',
            start='2015-07-18T14:41:12.809362',
            end='2017-07-18T14:41:12.809362',
            granularity=60)

print(hist[0][0],hist[-1][0])
```

1500369540 1500345720
which is 2017-07-18T14:49:00 2017-07-18T08:12:00 
Shouldn't the bucket start from 2015?

**Comment by mabounassif** [comment]
Maybe not relevant. Keep in mind that the request has a limit of 200 candles. So you are requesting 2 years of data for a granularity of 60 seconds. That well beyond 200 candles. That's why you may have just a cropped out bucket.
