### ISSUE TITLE
Getting SSLError => bad handshake

### ISSUE THREAD

**Issue by cyzanfar** [danpaquin/gdax-python#92]
`SSLError("bad handshake: SysCallError(54, 'ECONNRESET')` error when trying to call `get_product_ticker`. Any thoughts ?

**Comment by copland** [comment]
@cyzanfar You may have an outdated version of OpenSSL. I've seen this issue when running OpenSSL 0.9.8. To see which OpenSSL version you are running try the following command:

```
$ python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by cyzanfar** [comment]
@copland 

```
$ python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 0.9.8zh 14 Jan 2016
```
