### ISSUE TITLE
.get_product_ticker() hangs forever sometimes

### ISSUE THREAD

**Issue by garbb** [danpaquin/gdax-python#93]
With the following code, sometimes .get_product_ticker() hangs forever. Probably due to bad connection?
```python
import time

# Set a default product
publicClient = gdax.PublicClient(api_url='https://api.gdax.com')

while (True):
	# Get the product ticker for a specific product.
	btc_price = publicClient.get_product_ticker(product_id="BTC-USD")['price']
	print btc_price
	
	time.sleep(60)
```

Do you have any timeout set in your request?
see: http://requests.readthedocs.io/en/master/user/quickstart/#timeouts

> You can tell Requests to stop waiting for a response after a given number of seconds with the timeout parameter. **Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely**

May I suggest you include a default timeout of something like 30 seconds in order to prevent the possibility of the request hanging?

**Comment by garbb** [comment]
After adding the timeout parameter:
```python
r = requests.get(self.url + '/products/{}/ticker'
                         .format(product_id), timeout=10)
```
And letting the code run for a few days, I have confirmed that a ```requests.ReadTimeout``` occurred.

**Comment by danpaquin** [comment]
Commit e44a415 fixed this. Thanks!
