### ISSUE TITLE
sell() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by katelynsills** [danpaquin/gdax-python#96]
Hi all, I keep getting this error:

`TypeError: sell() takes 1 positional argument but 2 were given`

when I try to call `sell` like `response = authClient.sell(request)` where `request` is a dictionary.

The `sell` method looks fine, so I'm at a loss:

```
def sell(self, **kwargs):
        kwargs["side"] = "sell"
        r = requests.post(self.url + '/orders',
                          data=json.dumps(kwargs),
                          auth=self.auth)
        return r.json()
```

**Comment by katelynsills** [comment]
Realized my mistake. With the dictionary, it should be called like `authClient.sell(**request)`. Sorry for the confusion!

**Comment by danpaquin** [comment]
No worries! I make this mistake regularly
