### ISSUE TITLE
Updated to 1.0.6

### ISSUE THREAD

**Issue by Londo-Mollari** [danpaquin/gdax-python#98]
Hello, I updated to 1.0.6 and tried your sample code:

```
import gdax, time
publicClient = gdax.PublicClient()
order_book = gdax.OrderBook()
order_book.start()
time.sleep(10)
order_book.close()
```
And keep getting the following error:
```
Traceback (most recent call last):
  File "./book.py", line 10, in <module>
    order_book = gdax.OrderBook()
  File "/usr/local/lib/python2.7/dist-packages/gdax/order_book.py", line 20, in __init__
    self._client = PublicClient(product_id=product_id)
TypeError: __init__() got an unexpected keyword argument 'product_id'
```
I also noticed that I was receiving the same error when moving a program of mine from a production system running the pre-case-changes version of the library to the up-to-date system, even after making the case changes.  Any help is deeply appreciated, so thank you in advance.  I am using Python 2.7.9 on Linux

**Comment by metachris** [comment]
This seems to be fixed in the current master branch, but not yet released on PyPi.

**Comment by Londo-Mollari** [comment]
Hi Chris,
Thanks much.  I'll download the files directly from this repository and be sure to use a better subject next time.  The help is appreciated!
